### ISSUE TITLE
not all cars work

### ISSUE THREAD

**Issue by AtomicGaming666** [five-m/Vehicles#5] opened 2020-05-28 06:02 UTC
hey so i pot all the cop cars in my server but only to of them will load

**Comment by gabrielcalderon** [comment] 2020-05-29 22:18
I have the same problem, several of the police cars don't spawn at all. 

Ex.
Chiron
Reventon

**Comment by Declanoneil** [comment] 2020-06-28 19:22
@gabrielcalderon and @AtomicGaming666  ill have a look at the cars and see if i can fix them if i do ill let you know

**Comment by Declanoneil** [comment] 2020-06-28 19:25
the reason why the chiron police car doesnt work because theres is no car model for the car to work

**Comment by Declanoneil** [comment] 2020-06-28 19:25
so basically you have every part except the frame of the car

**Comment by WajihHalawani** [comment] 2020-07-24 00:05
Please keep in mind that not every car is tested before posting in here. But i can confirm that more than 95% of the pack is working fine.
@AtomicGaming666 

I'm closing this issue here. Thanks for the feedback!

**Closed by WajihHalawani** 2020-07-24 00:05 UTC

**Comment by MisterRipley** [comment] 2020-07-30 09:17
the nismo20 does not work it causes game to crash

**Comment by WajihHalawani** [comment] 2020-08-03 15:00
Next time please make a new issue request and don't spam other's issues with different issues please.

And no it doesn't.
